<?php
/**
 * Created by PhpStorm.
 * User: 一根小腿毛
 * Date: 2017/9/30
 * Time: 21:51
 */
/**
 * Created by PhpStorm.
 * User: 一根小腿毛
 * Date: 2017/9/30
 * Time: 21:51
 * api基础库
 */

namespace App\Controller;

 abstract class ApiController extends BaseController{

      /**
     * 返回错误信息
     * @author 一根小腿毛 <1368213727@qq.com>
     *
     * @param array $info
     * @param null $url
     * @param int $code
     * @param int $time
     * @return string
     */
    protected function error($info = [], $url = null, $code = 0,$time=10)
    {
        $this->sendJson(['msg'=>$info, 'url'=>$url, 'code'=>$code, 'status'=>false]);
    }

        /**
     * 成功返回数据
     * @author 一根小腿毛 <1368213727@qq.com>
     *
     * @param string $data
     * @param string $info
     * @param null $url
     * @param int $code
     * @param int $time
     * @return string
     */
    protected function success($data = '', $info = '', $url = null, $code = 1,$time=10)
    {
        $this->sendJson(['data'=>$data,'msg'=>$info, 'url'=>$url, 'code'=>$code, 'status'=>true]);
    }

     /**
      * 初始化
      * @author 一根小腿毛 <1368213727@qq.com>
      * @return string
      */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

}
