<?php
namespace App\Modules\Index\Controllers;

use App\Controller\BaseController;
use App\Models\admin\User;
use App\Models\common\Column;

abstract class ControllerBase extends BaseController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        if(explode(".",$_SERVER['HTTP_HOST'])[0] === "api"){
        	$this->response->redirect('http://'.str_replace("api.","",$_SERVER['HTTP_HOST']));
        }
    }
}
