<?php

namespace App\Modules\Api\Controllers;

use App\Models\common\Document;
use App\Models\common\DocumentFile;
use App\Modules\Api\service\FileService;
use App\Tools\QiniuDrive;

class FileController extends BaseController
{

    private $service;
    private $file_accept='zip,rar,txt,jpg,png,exe';
    private $accept_icon=[
        'zip'=>'document',
        'txt'=>'document-text',
        'rar'=>'android-document',
        'exe'=>'android-desktop',
        'jpg'=>'images',
        'png'=>'images',
    ];
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new FileService();
    }

    /**
     * 首页 返回列表 上传token
     * @author 一根小腿毛 <1368213727@qq.com>
     * @return string
     */
    public function indexAction()
    {
        $kw = $this->request->getPost("kw");
        $list = $this->service->get_list(0,24,$kw);
        $data = [];
        $data['u_token'] = (new QiniuDrive())->get_token(url('/notice/upload'));
        $data['data_list'] = $list->get_data();
        $data['u_accept'] = explode(",",$this->file_accept);
        $data['accept_icon'] = $this->accept_icon;
        $data['up_url'] = config("system.q_server");
        $this->success($data);
    }

    /**
     * 上传文件保存
     * @author 一根小腿毛 <1368213727@qq.com>
     * @return string
     */
    public function SaveAction(){
        $data =$this->request->getPost();
        if(!$data || !$data['title'] || !$data['file_id'] || is_int($data['open_status'])) $this->error('上传失败，参数错误');
        if(DocumentFile::where(['file_id'=>$data['file_id']])->order('file_id DESC')->_find()){
            $this->error('文件已经上传过了哦~','','-100');
        }
        $Model1 = new Document();
        $sql_data1['cid'] = isset($data['cid']) ? $data['cid'] : 0;
        $sql_data1['model'] = 6;
        $sql_data1['title'] = $data['title'];
        $sql_data1['shorttitle'] = $data['title'];
        $sql_data1['uid'] = $this->userInfo['id'];
        $sql_data1['status'] = $data['open_status'];
        $id = $Model1->_insert($sql_data1);
        if($id){
            $Model2 = new DocumentFile();
            $sql_data2['aid'] = $id;
            $sql_data2['file_id'] = $data['file_id'];
            $sql_data2['description'] = $data['desc'];
            $Model2->_insert($sql_data2);
            $this->success(['id'=>$id],'成功拉~');
        }else{
            $this->error("上传失败,错误:{$Model1->error}");
        }
    }

    /**
     * 删除
     * @author 一根小腿毛 <1368213727@qq.com>
     * @return string
     */
    public function DelAction(){
     $id = $this->request->getPost('id','int',0);
     if(!$id){$this->error('非法参数...');}
     $res = $this->service->del($id);
     if(!$res->is_success()){$this->error($res->get_message());}
     $this->success([],$res->get_data());
    }

    /**
     * 编辑保存
     * User: 一根小腿毛@QQ:1368213727
     */
    public function SaveEditorAction(){
        $title = $this->request->getPost('title');
        $description = $this->request->getPost('desc');
        $status = $this->request->getPost('open_status');
        $id = $this->request->getPost('id');
        if($id && $title && $description && in_array($status,[0,1])){
            $res = $this->service->edit(['id'=>$id],['title'=>$title,'description'=>$description,'status'=>$status]);
            if(!$res->is_success()){$this->error($res->get_message());}
            $this->success([],$res->get_data());
        }
        $this->error('请填写完整~');
    }


}

