<?php

namespace App\Modules\Api\Controllers;

use App\Models\common\Document;
use App\Modules\Api\service\MusicService;


class MusicController extends BaseController
{

    private $service;


    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new MusicService();
    }

    /**
     * 获取首页数据
     * @author 一根小腿毛 <1368213727@qq.com>
     * @return string
     */
    public function indexAction(){
        $h = service("api/music")->getHot(10)->get_data();
        $l = service("api/music")->getList()->get_data();
        $this->success(["hot"=>$h,"_list"=>$l]);
    }
    /**
     * 搜索音乐
     * @author 一根小腿毛 <1368213727@qq.com>
     * @return string
     */

    public function SearchAction()
    {
        $kw = $this->request->getPost('kw');
        $type = $this->request->getPost('type');
        if(!$kw) $this->error('请输入搜索内容~');
        //搜索自己音乐库
        $_list=[];
        if($type === "true") {
            $_list = service("api/music")->searchLocal($kw)->get_data()->toArray();
        }
        if(!$_list){//21
            $res = $this->service->search($kw,12,$this->request->getPost("s_page")? $this->request->getPost("s_page") : 1);
            $_list = $res->get_data();
        }
        if($type === "true"){
            service("api/music")->addMusic($_list);
            $_list = service("api/music")->searchLocal($kw)->get_data();
        }
        $this->success($_list);
    }

    /**
     * 收藏音乐
     * User: 一根小腿毛@QQ:1368213727
     */
    public function collectAction(){
        $id = $this->request->getPost("id","int",0);
        if($id){
            $is = Document::builder()
                ->InnerJoin('App\Models\common\DocumentMusic', 'b.aid=a.id', 'b')
                ->where(["a.uid"=>$this->userInfo['id'],"b.file_id"=>$id])
                ->field(['a.id'])
                ->_find();
            if($is){
                //删除
                $r = $this->service->del($is["id"]);
                if(!$r->is_success()) $this->error($r->get_message());
                $this->success([],"取消收藏成功了~");
            }else{
                //添加
                $r = $this->service->collect($id,$this->userInfo['id']);
                if(!$r->is_success()) $this->error($r->get_message());
                $this->success([],"收藏成功了~");
            }
        }else{
            $this->error("音乐不存在~");
        }
    }

}

