<?php
/**
 * 通知处理类
 * Created by PhpStorm.
 * User: 一根小腿毛
 * Date: 2017/10/2
 * Time: 11:18
 */

namespace App\Modules\Api\Controllers;

use App\Controller\BaseController;
use App\Models\admin\Attachment;
use App\Tools\QiniuDrive;

class NoticeController extends BaseController
{

    private $drive;

    /**
     * 初始化
     * @author 一根小腿毛 <1368213727@qq.com>
     * @return string
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->drive=new QiniuDrive();
    }

    /**
     * 视频上传回掉
     * @author 一根小腿毛 <1368213727@qq.com>
     * @return string
     */
    public function videoAction(){
        $_body = file_get_contents('php://input');
        $body  = str_replace("%2F","/",$_body);
        $res=$this->drive->video($body);
        $this->send_status($res);
    }

    /**
     * 普通上传回掉  这个回掉将只会入库并返回 id
     * @author 一根小腿毛 <1368213727@qq.com>
     * @return string
     */
    public function uploadAction(){
        $_body = file_get_contents('php://input');
        $body  = str_replace("%2F","/",$_body);
        $res=$this->drive->upload($body);
        $this->send_status($res);
    }

    /**
     * 相册照片上传
     * @author 一根小腿毛 <1368213727@qq.com>
     * @return string
     */
    public function uploadPhotosAction(){
        $_body = file_get_contents('php://input');
        $body  = str_replace("%2F","/",$_body);
        $res=$this->drive->upload_photos($body);
        $this->send_status($res);
    }


    /**
     *
     * @author 一根小腿毛 <1368213727@qq.com>
     *
     * @param string $field
     * @return string
     * @internal param 视频—— $string $field 回掉字段
     */
    public function handleVideoAction($field =''){
        if(isset(QiniuDrive::$handle_video[$field])){
            $Model = new Attachment();
            $notifyBody = file_get_contents('php://input');
            $this->drive->log_result($notifyBody);
            $_notifyBody= json_decode($notifyBody,true);
            $sname = $_notifyBody["inputKey"];
            $status = Attachment::where(['md5_key'=>$sname])->_value('status');
            if($status > -2){
                $data[$field] = $_notifyBody["items"][0]["key"];
                $data['status'] = ($status+1);
                if($Model->where(['md5_key'=>$sname])->_update($data)){
                    return true;
                }else{
                    $this->drive->log_result($Model->error);
                }
            }else{
                $this->drive->log_result("找不到name为{$sname}的数据");
            }
        }else{
            $this->drive->log_result($field.'不存在 self::$handle_video 中');
        }
    }
    /**
     * 头像上传回掉
     * @author 一根小腿毛 <1368213727@qq.com>
     * @return string
     */
     public function AvatarAction(){
          $_body = file_get_contents('php://input');
          $body  = str_replace("%2F","/",$_body);
          $res=$this->drive->avatar($body);
          $this->send_status($res);
     }

    /**
     * 编辑器上传内容回掉
     * User: 一根小腿毛@QQ:1368213727
     */
    public function uploadEditorAction(){
        $_body = file_get_contents('php://input');
        $body  = str_replace("%2F","/",$_body);
        $body  = json_decode($body,true);
        $this->send_status(["status"=>true,"code"=>200,"path"=>config("system.static_domain").'/'.$body['fkey']]);
    }
    /**
     * 回掉发送结果
     * @author 一根小腿毛 <1368213727@qq.com>
     * @return string
     * @param string $res
     */
      private function send_status($res = ''){
          if(!$res){
              $return = ['err' => '上传失败拉~'];
              $code=500;
          }else if($res['status'] === true){
              $return = ['ret' => 'success'];
              $code=200;
          }else{
              $return = [
                  'err' => isset($res['status']) ? $res['status'] : '上传失败',
              ];
              $code = isset($res['code']) ? $res['code'] : 500;
          }
          unset($res['status']);
          unset($res['code']);
        $this->sendJson(array_merge($return,$res),$code);
      }


}