<?php

namespace App\Modules\Api\Controllers;

use App\Models\common\Column;
use App\Modules\Api\service\PhotosService;
use App\Tools\QiniuDrive;

class PhotosController extends BaseController
{

    private $service;

    private $file_accept='gif,jpg,png';

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new PhotosService();
    }

    /**
     * 获取相册列表
     * @author 一根小腿毛 <1368213727@qq.com>
     * @return string
     */
    public function CoverListAction()
    {
      $res = $this->service->get_cover_list();
      $data = [];
      $data['u_token'] = (new QiniuDrive())->get_token(url('/notice/upload'));
      $data['u_url'] = config("system.q_server");
      $data['u_accept'] = explode(",",$this->file_accept);
      $data['data_list'] = $res->get_data();
      $this->success($data);
    }

    /**
     * 创建相册
     * @author 一根小腿毛 <1368213727@qq.com>
     * @return string
     */
    public function CoverAddAction(){
     $data = $this->request->getPost();
     if(!$data['title']) $this->error('请填写您的相册标题...');
     if(!$data['file_id']) $this->error('请上传相册封面...');
     if(!$data['desc']) $this->error('请填写您的相册描述...');
     if(empty($data['open_status'])) $this->error('请选择相册开放成度...');
     $model = new Column();
     $sql = [];
     $sql['pid'] = 0;
     $sql['uid'] = $this->userId;
     $sql['name'] = $data['title'];
     $sql['description'] = $data['desc'];
     $sql['model'] = 3;
     $sql['cover'] = $data['file_id'];
     $sql['status'] = 1;
     $sql['rank_auth'] = $data['open_status'];
     if($id = $model->_insert($sql)){
         $this->success($id);
     }else{
         $this->error($model->error);
     }
    }

    /**
     * 获取详情页数据
     * @author 一根小腿毛 <1368213727@qq.com>
     * @return string
     */
    public function GetDataAction(){
      $cid = $this->request->getPost('cid','int');
      $cate = Column::where(['id'=>$cid])->field('id,name,description,cover,update_time,rank_auth AS status')->_find();
      $cate= $cate ? $cate->toArray() : [];
      if($cate){
          $cate['cover'] = get_file_path($cate['cover']);
      }
      $list = $this->service->get_list($cid,12)->get_data();
        /**
         * 组成一个简单列表
         */
        $thumb_list=[];
        foreach ($list->items as $key=>$value){
            if($key > 8) {break;}
            $thumb_list[]=[
                  'uid'=>$key,
                  'name'=>$value->title,
                  'status'=>'done',
                  'url'=>config('web.q_host').'/'.$value->path.'?imageMogr2/thumbnail/300x/gravity/Center/crop/200x200',
            ];
        }
      $data=[];
      $data['token']=(new QiniuDrive())->get_token(url('/notice/uploadPhotos'),['cid'=>$cid]);
      $data['up_url']=config("system.q_server");
      $data['list']=$list;
      $data['cate']=$cate;
      $data['up_list']=$thumb_list;//上传处所列图列表
      $this->success($data);
    }



    /**
     * 删除相册
     */
    public function delCoverAction(){
        $id = $this->request->getPost('id');
        if($id){
            $res = $this->service->delete_cover($id);
            if(!$res->is_success()){$this->error($res->get_message());}
            $this->success([],$res->get_data());
        }else{
            $this->error('参数错误~');
        }
    }

    /**
     * 编辑相册
     */
    public function EditCoverAction(){
        $data =[];
        $data['name']=$this->request->getPost('title');
        $data['description']=$this->request->getPost('desc');
        $data['rank_auth']=$this->request->getPost('open_status',"int",0);
        $id = $this->request->getPost('id');
        if(Column::where(['id'=>$id])->_update($data)){
            $this->success('修改成功~');
        }else{
            $this->error('修改失败');
        }
    }

    /**
     * 设置封面
     * @author 一根小腿毛 <1368213727@qq.com>
     * @return string
     */
    public function settingPhotosAction(){
     $cate = $this->request->getPost('cate','int',0);
     $file_id = $this->request->getPost('id','int',0);
     if($cate && $file_id && Column::where(['id'=>$cate])->_update(['cover'=>$file_id])){
         $this->success('设置封面成功~');
     }else{
         $this->error('设置封面失败~');
     }
    }

    /**
     * 删除相片
     * @author 一根小腿毛 <1368213727@qq.com>
     * @return string
     */
    function delPhotosAction(){
        $id = $this->request->getPost('id','int',0);
        if(!$id){$this->error('非法参数...');}
        $res = $this->service->del($id);
        if(!$res->is_success()){$this->error($res->get_message());}
        $this->success([],$res->get_data());
    }

}

