<?php

namespace App\Modules\Api\Controllers;

use App\Controller\ApiController;
use App\Models\admin\User;

class SingController extends ApiController
{
    /**
     * 初始化
     * @author 一根小腿毛 <1368213727@qq.com>
     * @return string
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 登录
     * @author 一根小腿毛 <1368213727@qq.com>
     * @return string
     */
    public function loginAction()
    {
        $data = [];
        $data['username'] = $this->request->getPost('username','trim','');
        $data['password'] = $this->request->getPost('password','trim','');
        $res = service('api/sing')->login($data);
        if(!$res->is_success()) $this->error($res->get_message());
        $this->success($res->get_data(),'登录成功');
    }

    /**
     * 获取用户头像
     * @author 一根小腿毛 <1368213727@qq.com>
     * @return string
     */
    public function getAvatarAction(){
        $data = $this->request->getPost();
        if(!isset($data['username'])) $this->error('非法请求~');
        $username = trim($data['username']);
        $user = User::where(['username'=>$username])->field('avatar,bg')->_find();
        if($user){
            return $this->success(['avatar'=>get_file_path($user->avatar),"bg"=>$user->bg],'成功');
        }else{
            return $this->error('找不到这个用户~');
        }
    }

}

