<?php

namespace App\Modules\Api\Controllers;

use App\Models\common\Document;
use App\Models\common\DocumentVideo;
use App\Modules\Api\service\VideoService;
use App\Tools\QiniuDrive;

class VideoController extends BaseController
{
    //服务层
    private $service;
    private $file_accept;
    /**
     * 初始化
     * @author 一根小腿毛 <1368213727@qq.com>
     * @return string
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->file_accept = explode(",",config("system.vd_accept"));
        $this->service = new VideoService();
    }

    /**
     * 发布视频页
     * @author 一根小腿毛 <1368213727@qq.com>
     * @return string
     */
    public function indexAction(){
        $data = [
            'up_config'=>[
                'qiniu_token'=>(new QiniuDrive())->get_token(url('/notice/video')),
                'file_accept'=>$this->file_accept,
                'up_path'=>config("system.q_server"),
                '_accept_text'=>config("system.vd_accept"),
            ],
            'up_list'=>Document::builder()
                ->InnerJoin('App\Models\common\DocumentVideo', 'b.aid=a.id', 'b')
                ->InnerJoin('App\Models\admin\Attachment', 'b.file_id=c.id', 'c')
                ->where(["a.model"=>1,"a.uid"=>$this->userId,"trash"=>0])
                ->field([
                    'a.title,a.id',
                    'b.file_id,b.description',
                    'c.path,c.name,c.thumb,c.status'
                ])
                ->limit(0,12)
                ->order("a.sort DESC,a.id DESC")
                ->_select()
        ];
        return $this->success($data,'获取成功~');
    }
    /**
     * 视频列表
     * @author 一根小腿毛 <1368213727@qq.com>
     * @return string
     */
    public function videoListAction()
    {
      $kw = $this->request->getPost("kw");
      $res = $this->service->get_list(0,16,$kw);
      if(!$res->is_success()) $this->error($res->get_message());
      $this->success($res->get_data(),'获取成功');
    }

    /**
     * 视频详情
     * @author 一根小腿毛 <1368213727@qq.com>
     * @return string
     */
    public function videoDetailsAction(){
        $id = $this->request->getPost('id','trim',0);
        if(!$id) $this->error('非法参数~');
        $res = $this->service->get_info($id);
        if(!$res->is_success()) $this->error($res->get_message());
        $this->success($res->get_data(),'获取成功');
    }

    /**
     * 发布视频
     * @author 一根小腿毛 <1368213727@qq.com>
     * @return string
     * @return string
     */
    function PushAction(){
        $data =$this->request->getPost();
        if(!$data || !$data['title'] || !$data['file_id']) $this->error('上传失败，参数错误');
        if(DocumentVideo::where(['file_id'=>$data['file_id']])->order('file_id DESC')->_find()){
            $this->error('视频已经上传过了哦~','','-100');
        }
        $Model1 = new Document();
        $sql_data1['cid'] = isset($data['cid']) ? $data['cid'] : 0;
        $sql_data1['model'] = 1;
        $sql_data1['title'] = $data['title'];
        $sql_data1['shorttitle'] = $data['title'];
        $sql_data1['uid'] = $this->userInfo['id'];
        $sql_data1['status'] = $data['open_status'];
        $id = $Model1->_insert($sql_data1);
        if($id){
            $Model2 = new DocumentVideo();
            $sql_data2['aid'] = $id;
            $sql_data2['file_id'] = $data['file_id'];
            $sql_data2['description'] = $data['desc'];
            $Model2->_insert($sql_data2);
            $this->success(['id'=>$id],'成功拉~');
        }else{
            $this->error("上传失败,错误:{$Model1->error}");
        }
    }


    /**
     * 删除
     * @author 一根小腿毛 <1368213727@qq.com>
     * @return string
     */
    public function DelAction(){
        $id = $this->request->getPost('id','int',0);
        if(!$id){$this->error('非法参数...');}
        $res = $this->service->del($id);
        if(!$res->is_success()){$this->error($res->get_message());}
        $this->success([],$res->get_data());
    }

    /**
     * 修改
     * @author 一根小腿毛 <1368213727@qq.com>
     * @return string
     */
    public function EditAction(){
       $title = $this->request->getPost('title');
       $description = $this->request->getPost('desc');
       $status = $this->request->getPost('open_status');
       $id = $this->request->getPost('id');
       if($title && $description && in_array($status,[0,1])){
           $res = $this->service->edit(['id'=>$id],['title'=>$title,'description'=>$description,'status'=>$status]);
           if(!$res->is_success()){$this->error($res->get_message());}
           $this->success([],$res->get_data());
       }
       $this->error('请填写完整~');
    }

}

